### ISSUE TITLE
Missing PyPi dependency

### ISSUE THREAD

**Issue by HorlogeSkynet** [etingof/apacheconfig#10]
Hi Ilya,

'starting working with your module around here, and it looks like the dependency to `ply` is not explicitly set for PyPi.
Installing `apacheconfig` with `pip` does not automatically install `ply`.

Are you aware of this ?

Thanks, bye :wave:

**Comment by HorlogeSkynet** [comment]
Wow that is a **quick** fix :joy: 
I'm closing here and I'll tell you once the next PyPi build is up !

Have a nice day :sun_with_face:

**Comment by etingof** [comment]
apacheconfig 0.2.1 has been released on PyPI

**Comment by HorlogeSkynet** [comment]
It looks good on my own !
Thanks again
