### ISSUE TITLE
Parsing then writing a config file adds syntax errors

### ISSUE THREAD

**Issue by daladim** [etingof/apacheconfig#101]
Hi,
Thanks for apacheconfig. It has issues however, and some Apache drective are not handled as they should.

For instance, the following code turns the example config file into a defective version
**code**
```
import apacheconfig
with apacheconfig.make_loader(useapacheinclude=False) as loader:
        config = loader.load("/path/to/config.conf")
print(loader.dumps(config))
```

**original config file**
```
<IfModule mod_ssl.c>
    Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains
    <Directory />
    Require all denied
    Options None
    AllowOverride None
    </Directory>
</IfModule>
```

**modified config file**
```
<IfModule>
  <mod_ssl.c>
        Header "always set Strict-Transport-Security "max-age=31536000; includeSubDomains""
        <Directory>
          </>
            Require "all denied"
            Options None
            AllowOverride None
          <//>
        </Directory>
  </mod_ssl.c>
</IfModule>
```

(as stated in the Readme), this module changes the way the config file looks, but it also changes what they mean, which is not expected.
In this example, it has broken directives that have arguments (and Apache complains that, e.g. `<IfModule> directive requires additional arguments`), and has added quotes where it shouldn't.

Also, it would be great that comments were kept, even though I understand that it is hard to keep them due to the dictionary-like object the file is converted into.

I am using Python 3.7.3 and apacheconfig version 0.3.2 (installed from pip).

**Comment by uriariel** [comment]
I also tackled this issue, it's very annoying

**Comment by uriariel** [comment]
More over this issue arises when parsing commands with multiple arguments

**Comment by daladim** [comment]
For those interested, I have solved my issues using (and fixing) another module to handle Apache files, available [in my fork of parse_apache_configs](https://github.com/daladim/parse_apache_configs), and a merge request to the upstream repo is pending
