### ISSUE TITLE
Some troubles with `ApacheIncludesLexer`

### ISSUE THREAD

**Issue by HorlogeSkynet** [etingof/apacheconfig#12]
Hey Ilya, one more issue from me !

It looks like there is a problem with the `ApacheIncludesLexer` 'cause `Include` operations do not work when they looks like :

```apache
Include conf.d/*.conf
```

... due to the `'I'`, and because the token is `'include[\t ]+[^\n\r]+'` (and case-sensitive).

It has been a headache to debug, and I don't know how to solve this problem as you instanciate only one `lex` element for the whole parsing, and because of course the case-sensitivity could be important in some cases.

It works well if we change the line to :

```apache
include conf.d/*.conf
```

Thanks again, have a good WE :ok_hand: 

EDIT : Well... We could add a new token doing the same job but with a `'I'`... Maybe there is a cleaner solution ?

**Comment by etingof** [comment]
Thank you for digging into this!

Looking at [the Perl code](https://metacpan.org/source/TLINDEN/Config-General-2.63/General.pm#L769), does it look like `include` (and apparently `includeoptional` which is not yet supported) is being matched case-insensibly? In that case I'd be inclined just add `I` to the existing regexp...

WDYT?

**Comment by HorlogeSkynet** [comment]
Ahah yeah the `/i` at the end does not lie : their implementation is effectively case-insensitive 😯

**Comment by etingof** [comment]
Case-insensitive include statements should work since commit 50c6101607df7ffd2aa3cbfc2c691ebc69490f78

**Comment by HorlogeSkynet** [comment]
Interesting change !
You're a machine, thanks again for your work / support.

I'll keep you posted as usual :smile: 

Enjoy your WE
