### ISSUE TITLE
Extra spaces at end are not trimmed

### ISSUE THREAD

**Issue by bpradeep20** [etingof/apacheconfig#17]
**Config:**
```
<main>
    key value 
</main>

```
(There is one space extra after value. i.e, key value<space>)

With perl parser, extra space at end is trimmed off.
```
$VAR1 = {
          'main' => {
                      'key' => 'value'
                    }
        };

```

with python parser, space at end is not trimmed
```
{
    "main": {
        "key": "value "
    }
}

```

**Comment by HorlogeSkynet** [comment]
Hi, what a coincidence ! See #18

**Comment by etingof** [comment]
Thank you for rising this! Once #18 is merged, does that fix the issue you've run into?

**Comment by etingof** [comment]
I assume this is fixed. Feel free to reopen this issue otherwise. ;)
