### ISSUE TITLE
Use of same `ApacheConfigError` makes debugging harder

### ISSUE THREAD

**Issue by HorlogeSkynet** [etingof/apacheconfig#19]
Hey,

Let's take a look at a likely case :

* A first config file uses `IncludeOptional` instruction
* This makes the parser trying to load some extra files
* If a parsing error is thrown during the loading of those files, it will be catched by the https://github.com/etingof/apacheconfig/blob/master/apacheconfig/loader.py#L202 statement and thus totally silenced for the developer :confused: 

The point is : The module should use different `Error` classes to allow distinction between them.

Tell me what you think about that !

Have a good day :sun_with_face: 

EDIT : FYI, if there is a problem with interpolated variables in one file for instance, the whole iteration (for `includeglob` and surely `includedirectories`) is stopped.
Each `g_include` call should watch for throwed exceptions coming from `load` or `_merge_contents` instead of letting them being catched by `g_includeoptional` parent call. WDYT ?

**Comment by etingof** [comment]
Let's see if commit d2ff43606393851b8990d1fb6a9d318061cc7932 improves the situation?

**Comment by HorlogeSkynet** [comment]
Your commit has definitely "fixed" the debugging difficulty I had experienced earlier with our specific case ; Thanks again :muscle:
