### ISSUE TITLE
Provide ability to save config similar to Perl's Config::General module.

### ISSUE THREAD

**Issue by bpradeep20** [etingof/apacheconfig#2]
Can we please add ability like save config (https://metacpan.org/pod/Config::General#SaveConfig()) which are available in  Perl's Config::General module.

**Comment by etingof** [comment]
Thanks for rising this!

One thing I am not certain about is how to deal with possible changes in loaded config... Some vars can get interpolated, some includes can get merged etc. Should we save the end result of the loader thus possibly changing the saved config?

On the other hand, it is in power of the user to disable all destructive changes to the data being loaded to ensure no information loss in the saved data...

**Comment by etingof** [comment]
Alright, simplistic implementation can be found in PR https://github.com/etingof/apacheconfig/pull/5 . Appreciate your testing/feedback. ;)

**Comment by etingof** [comment]
Hopefully, fixed in master.
