### ISSUE TITLE
Comment at end of value are not considered as comments

### ISSUE THREAD

**Issue by bpradeep20** [etingof/apacheconfig#21]
**Config**

```
<main>
    key value # comment1
    # comment2
</main>
```

With python parser
```
{
    "main": {
        "key": "value # comment1"
    }
}

```

with perl parser
```
$VAR1 = {
          'main' => {
                      'key' => 'value'
                    }
        };

```

Can you please check?

P.S.: You are awesome.

**Comment by etingof** [comment]
Commit 913dbafcbc7d3c57105c9c57042e608e5f2f33bc (in master) should have fixed that. Though hash escape (`\#`) is not yet supported.

**Comment by bpradeep20** [comment]
Thanks for the quick fix. Will you be providing support for escaping hash "\#"?

**Comment by bpradeep20** [comment]
Will you be providing support for escaping hash "#"?
