### ISSUE TITLE
dumps result is different than expected

### ISSUE THREAD

**Issue by cmakara** [etingof/apacheconfig#28]
Hello,

I would have a question.
I have a config like the following:
```
<thing-pool 123>
  thing thing1
  thing thing2
</thing-pool 123>
```
After loading it the given dict looks ok.
```
"thing-pool": [
          {
            "123": {
                "thing": "thing1"
            }
        }
]
```

But after dumping this dict I get the following: 
```
<thing-pool>
  <123>
    thing "thing1"
    thing "thing2"
  </123>
</thing-pool>
```

My question is if I can somehow force the dump to use the structure like on the top?

**Comment by etingof** [comment]
You may want to try the `namedblocks=False` options implemented in master (commit b619f3f259f31b6ab5921cff3107c7f5873bed9e).

I'd appreciate your feedback on this change.
