### ISSUE TITLE
Handle backslash at end so that it doesn't consider line after blank line

### ISSUE THREAD

**Issue by bpradeep20** [etingof/apacheconfig#34]
For config file:

```
<main>
   key1 abc \
        pqr\

   key2 value2
</main>
```

This is parsing it into:

{"main": {"key1": "abc         pqr   key2 value2"}}

while expected parsing is
{"main": {"key1": "abc         pqr   ", "key2":  "value2"}}

Also for config:

```
<main>
   key1 abc \
        pqr\

   <tag>
        key2 value2
    </tag>
</main>
```

It is raising below error:

>     raise ApacheConfigError("Parser error at '%s'" % p.value if p else 'Unexpected EOF')
> apacheconfig.error.ApacheConfigError: Parser error at 'main'

Can you please check?

**Comment by etingof** [comment]
You may want to check out commit 1751853f2fa3b8200ef7394c3d2ad1c2e5428c14 (which is in current master).
