### ISSUE TITLE
white space not ignored when key value pair splits in multiple lines

### ISSUE THREAD

**Issue by Sumit3** [etingof/apacheconfig#39]
for the file 
```
<mytag>
		key1 		this is a \
				very long line
</mytag>
```
the perl parser produces 
```
{
  "mytag": {
    "key1": "this is a very long line"
  }
}
```
where as the python parser produces 
```
{
  "mytag": {
    "key1": "this is a \t\t\t\tvery long line"
  }
}
```
The python parser doesn't ignores spaces if key value pair is splitting in multiple lines

**Comment by etingof** [comment]
@sydneyli By chance, the patch you are working on, would it be able to (conditionally ?) preserve white spaces?

**Comment by sydneyli** [comment]
Good idea! i'll try to work in a fix for this issue at some point as well.

**Comment by sydneyli** [comment]
Is this the expected behavior when the key / value pair is on a single line?
