### ISSUE TITLE
Convert inmemory loaded file into dict

### ISSUE THREAD

**Issue by Sumit3** [etingof/apacheconfig#40]
Currently to use the library we need to provide the file path as below 

```
with make_loader() as loader:
    config = loader.load('httpd.conf')
```
However if the file is already loaded in the memory (say as a string), is there any way to convert directly from that  in-memory loaded file into dict.

**Comment by etingof** [comment]
Could you may be use [.loads()](https://github.com/etingof/apacheconfig/blob/master/apacheconfig/loader.py#L327) call directly?

**Comment by Sumit3** [comment]
Works. Thanks !!
