### ISSUE TITLE
ConfigFileReadError: Config file "ports.conf" not found in search path

### ISSUE THREAD

**Issue by ogaida** [etingof/apacheconfig#41]
Hi Ilya,

First, thank you very much for your helpful project. 

if i run :

```
from apacheconfig import *

options = {
    'lowercasenames': True,
    'useapacheinclude': True,
    'includerelative': True,
    'includedirectories': True,
    'includeglob': True
}

with make_loader() as loader:
    config = loader.load('/etc/apache2/apache2.conf')

print(config)
```

and i get

```
$ python apache_config.py
Traceback (most recent call last):
  File "apache_config.py", line 12, in <module>
    config = loader.load('/etc/apache2/apache2.conf')
  File "/usr/local/lib/python2.7/dist-packages/apacheconfig/loader.py", line 385, in load
    return self.loads(f.read(), source=filepath)
  File "/usr/local/lib/python2.7/dist-packages/apacheconfig/loader.py", line 349, in loads
    self._ast_cache[source] = self._walkast(ast)
  File "/usr/local/lib/python2.7/dist-packages/apacheconfig/loader.py", line 325, in _walkast
    return handler(ast[1:])
  File "/usr/local/lib/python2.7/dist-packages/apacheconfig/loader.py", line 39, in g_config
    items = self._walkast(subtree)
  File "/usr/local/lib/python2.7/dist-packages/apacheconfig/loader.py", line 325, in _walkast
    return handler(ast[1:])
  File "/usr/local/lib/python2.7/dist-packages/apacheconfig/loader.py", line 92, in g_contents
    items = self._walkast(subtree)
  File "/usr/local/lib/python2.7/dist-packages/apacheconfig/loader.py", line 325, in _walkast
    return handler(ast[1:])
  File "/usr/local/lib/python2.7/dist-packages/apacheconfig/loader.py", line 261, in g_include
    raise error.ConfigFileReadError('Config file "%s" not found in search path %s' % (filename, ':'.join(configpath)))
apacheconfig.error.ConfigFileReadError: Config file "ports.conf" not found in search path .
```

i have an Ubuntu 16.04.1 LTS with Apache/2.4.18 (Ubuntu)

kind regards!
Oliver

**Comment by etingof** [comment]
Hey Oliver,

I suspect that your `apache2.conf` includes `ports.conf` file one way or the other e.g. may be indirectly. Try adding all paths where config files can possibly reside via the `--configpath` option.

Enabling debugging may help figuring out the config files being imported.

**Comment by ogaida** [comment]
Hi Ilya,

it does not help. My new script:

```
$ cat apache_config.py 
from apacheconfig import *

options = {
    'lowercasenames': True,
    'useapacheinclude': True,
    'includerelative': True,
    'includedirectories': True,
    'includeglob': True,
    'includerelative': True,
    'configpath': ['/etc/apache2']
}

with make_loader() as loader:
    config = loader.load('/etc/apache2/apache2.conf')

print(config)
```

I get the same error.

Anyway, in https://httpd.apache.org/docs/2.4/en/mod/core.html#include will be described, how files can be included. So it should alway be enough to use the informations from the main-config file. For example i have the serverroot:

```
$ grep -iP '^[^#].*root' /etc/apache2/apache2.conf
ServerRoot "/etc/apache2"
```
So from https://httpd.apache.org/docs/2.4/en/mod/core.html#include should be clear that this path is the root for relativ includes:

```
$ grep -P '^[^#].*ports.conf' /etc/apache2/apache2.conf
Include ports.conf  
```

Kind regards
Oliver

**Comment by etingof** [comment]
One thing to keep in mind is that the `apacheconfig` tool is a context free parser in the sense that it does not interpret Apache directives.

I think the code above does not make use of the `options` dict. It should be passed to `make_loader` perhaps. Is it the same with the code you are working on now?

**Comment by ogaida** [comment]
oh sorry, i thought it would be a parser for Apache-Webserver-Config. I got a first result after i took the options hash in the make_loader call: `make_loader(**options)`
