### ISSUE TITLE
Writable loader.py interface

### ISSUE THREAD

**Issue by sydneyli** [etingof/apacheconfig#49]
Thought I'd create an issue for more thorough discussion about this!

`loader.py` transforms the apache configuration into a Python dict. Although we can write this configuration to a new file, a lot of information isn't saved by a Python dict-- for instance, whitespace and field ordering.

We're looking to be able to alter fields, then write them back to a file without changing the parts of the file that we did not change.

**Comment by etingof** [comment]
Just noting #45, #47 in the context of this effort.

**Comment by sydneyli** [comment]
This is the high-level API we'll probably be working with going forward!

Generic Node
 * dump (handle)
   * dumps the nodestuff to a file handle
 * type  => string
   * read-only property, returns typestring

Contents Node ( Generic Node )
 * add (index, node)
 * remove (index) => node
 * iterator

Item Node [comment, statement, or include] ( Generic Node )
 * value (string)
   * r/w property, retrieve or set string

Block Node ( Contents Node )
 * contents operations operate on contents of block
 * name (string)
   * r/w property, alters block name (like `<block name> </block>`)
 #overridden `value` property operates on block name

**Comment by etingof** [comment]
Looks good to me. A few nitpicks though.

> This is the high-level API we'll probably be working with going forward!
> 
> Generic Node

Is `Generic Node` going to be used directly? If not, may be it could be an abstract base class?

> 
> * dump (handle)
>   
>   * dumps the nodestuff to a file handle

I think `file-like object` is a more conventional term with Python. That also refers to file object protocol/interface that your code would expect. That is not necesserily a disk file as such.

> * type  => string

Considering Py2 support, is it a `unicode` string?

>   * read-only property, returns typestring

What exactly is `typestring`?

> Contents Node ( Generic Node )
> 
> * add (index, node)
> * remove (index) => node

Can `Block Node` be added/removed? If yes, would it make sense to also have a way to address it by name, not only by index?

> * iterator
> 
> Item Node [comment, statement, or include] ( Generic Node )
> 
> * value (string)

For comments, it's likely to be `unicode`.

>   * r/w property, retrieve or set string

Is this some other attribute, not `value`?

> Block Node ( Contents Node )
> 
> * contents operations operate on contents of block

May be expand a bit on what those operations are? I am looking to understand how `Block Node` is different from `Contents Node`. ;-)

> * name (string)
>   
>   * r/w property, alters block name (like `<block name> </block>`)
>     #overridden `value` property operates on block name

Can there be unnamed blocks?

**Comment by sydneyli** [comment]
> Is Generic Node going to be used directly? If not, may be it could be an abstract base class?

Yes, it'll be an abstract class! Specified it more directly.

>I think file-like object is a more conventional term with Python. That also refers to file object protocol/interface that your code would expect. That is not necesserily a disk file as such.

:+1: 

> Considering Py2 support, is it a unicode string?

Yes, they'll be unicode strings (so Py3 regular strs, iirc?)! Will specify.

> What exactly is typestring?

`typestring` is the type that is exposed by the AST. I'm trying to find a better name for it-- but essentially, it may carry semantic meaning (like `include` or `statement`) that is relevant to the caller even if the structural type (`ItemNode`) is the same across `include` or `statement`. It's the first element in any node returned by `parser.py`.

> Can Block Node be added/removed? If yes, would it make sense to also have a way to address it by name, not only by index?

Since duplicate blocks can exist in a config, we'd like to use the index to be more specific. In any case, if the caller can iterate over Contents, the caller can also match on type (BlockNode) and name to implement this-- we'd like to start with a minimal API and build on top of it!

> Is this some other attribute, not value?

Nope, this is just describing what value is.

> May be expand a bit on what those operations are? I am looking to understand how Block Node is different from Contents Node. ;-)

Oh, sure! The contents node will only appear at the root-level and inside `<block/>`s. Since it's a collection of anything other than itself (blocks & items). I specified the operations above-- they operate on the contents contained within the block; I think we still need a separate node since block does have the `name` property that we need to know.

> Can there be unnamed blocks?

Ah, I messed up the API when transferring it. A block has a required name, but an optional value. For instance:
```
<blockname blockvalue>
  # comment
</blockname>
```

I edited the above post to address your comments.

**Comment by sydneyli** [comment]
PRs are up! Note, I haven't gotten a chance yet to implement the writable loader for non-Apache specific config features like here-documents and c-style comments-- I can create Issues for those if these PRs get through!
