### ISSUE TITLE
Support for  hash escape.

### ISSUE THREAD

**Issue by bpradeep20** [etingof/apacheconfig#51]
Can we please have support for hash escaping.

```
<main>
    key value\#123 
</main>
```

Perl parser:

```
{
    "main": {
        "key": "'value\\#123"
    }
}
```

Python parser:

```
{'main': {'key': 'value#123'}}
```

**Comment by etingof** [comment]
I am curious if @sydneyli has touched this matter while refactoring the parser lately?

**Comment by sydneyli** [comment]
Yes, I encountered it! Happy to take a stab at it in a bit :)
