### ISSUE TITLE
NoEscape option of Config::General

### ISSUE THREAD

**Issue by bpradeep20** [etingof/apacheconfig#6]
Are there plans to add some option for "NoEscape" equivalent in this python version?

From perldoc:
-NoEscape
If you want to use the data ( scalar or final leaf ) without escaping special character, turn this parameter on. It is not enabled by default.

**Comment by etingof** [comment]
Let's see if https://github.com/etingof/apacheconfig/pull/7  implements what you need?

**Comment by etingof** [comment]
Hopefully, fixed in master.
