### ISSUE TITLE
Support for multi-line block tags

### ISSUE THREAD

**Issue by sydneyli** [etingof/apacheconfig#61]
Perl's General::Config has support for multi-line block tags. Something like:
```
<block \
  with a \
  multiline name\
>
</block>
```
gets turned into:
```'block' => { 'with a multiline name' => {} }```

As it is now, multi-line block tags are parsed as option-value statements, which leads to parsing errors later down the line.

**Comment by etingof** [comment]
Oh, that must be a significant nuisance for those folks who have to parse such tags.

It looks like a missing parity feature (if not a bug) to me.

If you, by chance, could look into that - would be awesome! Thanks!
