### ISSUE TITLE
Option for multi-line hash comments

### ISSUE THREAD

**Issue by sydneyli** [etingof/apacheconfig#62]
Native apache has support for multi-line hash comments, such as:
```
# here is a \
   multi-line hash comment
```
where the entire body is interpreted to be a part of the hash comment.

Perl's General::Config doesn't seem to support this, but maybe we can provide an option for it.

**Comment by etingof** [comment]
+1 from me! Looks neat from usability standpoint.

**Comment by sydneyli** [comment]
Done in #65
