### ISSUE TITLE
Incorrect parsing of line with only key

### ISSUE THREAD

**Issue by bpradeep20** [etingof/apacheconfig#8]
For config file:
```
<main>
   key1
   key2 value2
</main>

```

python parser is parsing into
```
{  
   "main":{  
      "key1":"key2 value2"
   }
}
```

while perl parse will parse into
```
{  
   "main" => {  
      "key1"=> undef,
      "key2"=> "value2"
   }
}
```

Can this be handled?

**Comment by etingof** [comment]
Will https://github.com/etingof/apacheconfig/pull/9 help here?

**Comment by etingof** [comment]
Hopefully, fixed in master.

**Comment by bpradeep20** [comment]
Hi,

This is now failing to parse config.

```
<main>
   key1
   key2 value2
</main>
```
    raise ApacheConfigError("Illegal character '%s'" % t.value[0])
apacheconfig.error.ApacheConfigError: Illegal character 'k'

Can you please check?

**Comment by Sumit3** [comment]
Hi , did you get any chance to look into this issue ?

**Comment by etingof** [comment]
Hey, sorry, being overwhelmed by other things at the moment. If you have time to look into this, I'd happily handle your PR though. ;-)
