### ISSUE TITLE
dumps does not handle certain options correctly

### ISSUE THREAD

**Issue by duper51** [etingof/apacheconfig#81]
**The issue**

I'm currently running on the latest master branch of `apacheconfig` for testing purposes. I am unable to correctly grab options such as LocationMatch, Directory, and VirtualHost from an Apache config file and dump them to string. The option gets correctly picked up into the config dict, but when I run `dumps`, it converts the directive's option into it's own directive.

**Minimal Test Case**
```python
import apacheconfig as ac

configFile = """<VirtualHost *:80>
  ServerName orange.com
</VirtualHost>
"""

_options = {
    'configpath': '/etc/apache2',
    'includeglob': True,
    'multilinehashcomments': True
}
with ac.make_loader(**_options) as loader:
    configStruct = loader.loads(configFile)
    print(loader.dumps(configStruct))
```

I would expect it to output essentially the same data as what was contained in the string, however, it returns the following:

```
<VirtualHost>
  <*:80>
    ServerName "orange.com"
  </*:80>
</VirtualHost>
```

**Comment by etingof** [comment]
Have you tried disabling the [namedblocks](https://github.com/etingof/apacheconfig#namedblocks) feature?

**Comment by duper51** [comment]
Welp, that'll do it, that definitely worked there. Is it possible to change this behavior only on `dumps` and not in the initial `loads`?

**Comment by etingof** [comment]
That should be doable by creating two flavors of loaders with different set of options. One of them would read your file, the other would dumps it. Does it make sense?

**Comment by duper51** [comment]
Sure does! Thanks for the help!

**Comment by duper51** [comment]
Actually, now I have a new behavior.
```
<VirtualHost *:80   DocumentRoot "//var/www/html"
  ServerName "test.co"
  ErrorDocument "404 "404: File not found.""
  ErrorDocument "403 "403: Access denied.""
</VirtualHost *:80>
```

This seems to happen for all the VHosts in the file. I'm using the same sample code as above, just with `namedblocks` disabled.
